// scripts/testRender.cjs
// Run with: node scripts/testRender.cjs
// This script uses CommonJS (.cjs) so `require` works even if package.json has "type":"module".

// Ensure CSS imports from compiled templates are ignored
require('ignore-styles');

const path = require('path');
const fs = require('fs');

// require your generator (adjust path if utils is elsewhere)
const { renderPdfBuffer } = require(path.resolve(__dirname, '..', 'utils', 'generatePDF.cjs'));

(async () => {
    try {
        // Minimal sample formData — adapt to match your templates' expected fields
        const formData = {
            name: 'Test User',
            title: 'Safety Officer',
            email: 'test@example.com',
            summary: 'Generated by testRender',
            experience: [
                {
                    title: 'Safety Officer',
                    company: 'Acme Co',
                    startDate: 'Jan 2020',
                    endDate: 'Present',
                    description: '• Managed safety\n• Reduced incidents'
                }
            ],
            education: [],
            certifications: [],
            skills: ['Safety', 'Reporting'],
            languages: [],
            photo: null // optional: data URI or URL
        };

        console.log('Calling renderPdfBuffer with template "modern"...');
        const buf = await renderPdfBuffer({ formData, template: 'modern' });

        const outPath = path.resolve(process.cwd(), 'out-test.pdf');
        fs.writeFileSync(outPath, buf);
        console.log('✅ Wrote', outPath, 'size:', buf.length);
        process.exit(0);
    } catch (err) {
        console.error('❌ testRender error:', err);
        process.exit(1);
    }
})();
